### ISSUE TITLE
Need a clear tutorial or an example on how to use this library it's very confusing to get started.

### ISSUE THREAD

**Issue by pythonhubpy** [ambianic/peerjs-python#33]

**Comment by rudneff13** [comment]
totally agree. how to use it?

**Comment by ivelin** [comment]
I agree. 

[This blog post](https://webrtchacks.com/private-home-surveillance-with-the-webrtc-datachannel/) provides some information how it works and how it can be used, but a dedicated usage doc with examples would be great. Contributions are most welcome!

The usage is very similar to the original peerjs usage. The API is ported as closely as possible and its tested against the browser based peerjs code.

The closest thing we have currently as a real world usage example is this:
 https://github.com/ambianic/peerjs-python/blob/master/src/peerjs/ext/http-proxy.py

It is used by [ambianic edge](https://github.com/ambianic/peerjs-python/blob/master/src/peerjs/ext/http-proxy.py) to connect with [ambianic ui](https://github.com/ambianic/ambianic-ui/blob/master/src/remote/peer-fetch.js).

Contributions to the README doc with usage examples are most welcome.

**Comment by snroeust** [comment]
in the meantime, are there more accurate examples ? 
i have tried the http_proxy.py but i am stuck because i have my own peerjs, stun and turn server running, i can connect to the peerjs server but i get an error message when calling the peer room url.
to the peerjs server, but i get an error message when i call the peer room url

the error message looks like this: 
"Error while trying to join local peer room. Will retry in a few moments. Error: 
ConnectionError('Unexpected status code 404 for https://fpvhd.de:3001/peerjs/44e138eb-bc20-4ba5-8269-875c948bfa57/17912d04-ca4a-4e64-9162-14b974271343/room/id?ts=7
4314.40597430.6465509159039176')"

this also makes sense, because I don't have this root in my prohect, rather the form https://fpvhd.de/video/device/5feb50277e59d847fec072fb
where fpvhd.de is my website.

Is there any way to change this url ? 

I have seen it is created with the options of a peer object in the API class.
but I don't know if I can change it accordingly.

**Comment by ivelin** [comment]
> in the meantime, are there more accurate examples ?

Not that I am aware of. Please feel free to share your example as you make progress.

> i have tried the http_proxy.py but i am stuck because i have my own peerjs, stun and turn server running, i can connect to the peerjs server but i get an error message when calling the peer room url.
> to the peerjs server, but i get an error message when i call the peer room url

> the error message looks like this:
> "Error while trying to join local peer room. Will retry in a few moments. Error:
> ConnectionError('Unexpected status code 404 for https://fpvhd.de:3001/peerjs/44e138eb-bc20-4ba5-8269-875c948bfa57/17912d04-ca4a-4e64-9162-14b974271343/room/id?ts=7
> 4314.40597430.6465509159039176')"
> 
> this also makes sense, because I don't have this root in my prohect, rather the form https://fpvhd.de/video/device/5feb50277e59d847fec072fb
> where fpvhd.de is my website.
> 
> Is there any way to change this url ?
> 
> I have seen it is created with the options of a peer object in the API class.
> but I don't know if I can change it accordingly.

You will need to run the [ambianic pnp server](https://github.com/ambianic/ambianic-box) (fork of PeerJS server). It preserves the original functionality and adds a plug-in for room management. There is an [open issue to merge into peerjs server](https://github.com/peers/peerjs-server/issues/154), which is still gathering community support votes.


>
