### ISSUE TITLE
Video/Audio Connection

### ISSUE THREAD

**Issue by el07694** [ambianic/peerjs-python#40]
Is this ok to implement the video/audio connection part of peerjs?

**Comment by ivelin** [comment]
Sure thing. Go for it.

**Comment by snroeust** [comment]
Firstly thank you for this very interesting library, I have been looking at it and using it for a while and have been able to successfully establish a data connection via my own peerjs signaling server to my JavaScript code on my website, thank you very much for that. 

I would be really happy if I could get a video connection from my python script to a client that loads the website, I read a bit into the library and saw that everything is already provided for stream and call and now only a "MediaConnection" would have to be created, I wanted to ask how far the implementation for a video connection is or if you could possibly help or already try out prototypes. 

Thanks a lot

**Comment by ivelin** [comment]
Happy to hear that this library has been of help to you.

Media should be possible since aiortc supports it.

I think the biggest weak spot for us now is lack of an interop testsuite
that makes the library very brittle and susceptible to breaking
applications if anything changes on the PeerJS side of things.

I’ve opened an issue and discussed it with the PeerJS team:
https://github.com/peers/peerjs/issues/759

If you have any cycles to spare, this would be a place to start. Once we
have some confidence in the current code base stability , it should be
easier to add media and other features.

Ivelin

**Comment by ivelin** [comment]
@el07694 Are you still working on the video connection part?
