### ISSUE TITLE
Packaging fails on Python 3.9

### ISSUE THREAD

**Issue by ivelin** [ambianic/peerjs-python#46]
See https://github.com/ambianic/peerjs-python/pull/45 and https://github.com/ambianic/peerjs-python/pull/44 .

**Comment by amotl** [comment]
Hi Ivelin,

when exploring the root cause
```
src/av/codec/codec.c:6117:36: error: ‘AV_CODEC_CAP_HARDWARE’ undeclared (first use in this function); did you mean ‘AV_CODEC_CAP_DR1’?
```

I found https://github.com/PyAV-Org/PyAV/issues/651 and https://github.com/aiortc/aiortc/issues/326, which somehow suggest the build needs `ffmpg > 4` and maybe other updated libraries.

Apart from that, https://github.com/PyAV-Org/PyAV/issues/619#issuecomment-619538051 states that
> As of PyAV 8.0.0, binary wheels are provided which will greatly simplify installation and should solve your issue.

Unfortunately, there are no binary wheels for Python 3.9 yet, see [1]. @Odianosen25 observed the same within https://github.com/PyAV-Org/PyAV/issues/697. So, we probably should add a friendly question at [2], asking whether building and uploading binary wheels for Python 3.9 to PyPI would be possible.

With kind regards,
Andreas.

[1] https://pypi.org/project/av/#files
[2] https://github.com/PyAV-Org/PyAV/issues

**Comment by amotl** [comment]
Apparently, all dependency packages regarding `ffmpeg` and friends are satisfied with `ubuntu-20.04` already. So, #47 already fixes the build on GHA.
